Pack Management version 1.1.0
Nottingham-CTU/REDCap-Pack-Management pull request #2
Opened 2024-12-17 10:22 UTC by richdooley

* Bug fix: Corrected cron job to handle 0 active projects.

2025-03-26 09:57 UTC, NicholasHilken commented on packs_add.php
> +						elseif ( ! preg_match( '/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|' .
This looks like it is validating for a date time field.  I notice that the lang files have British English and English versions, and also have some date field labels, but I didn't notice a date format prompt.  I think that would be important to include somewhere.  Sorry - I'm rubbish at reading regex, but this looks like yyyy-mm-dd hh:mm which if it is, is fine for UK/US compatibility.

2025-03-26 09:58 UTC, NicholasHilken commented on packs_add.php
> +				elseif ( ! preg_match( '/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])' .
Perhaps define a constant for regularly reused regex strings?

2025-03-26 10:33 UTC, NicholasHilken commented on packs_edit.php
> +$queryCategory = $module->query( 'SELECT ems.`value` FROM redcap_external_module_settings ems ' .
Pretty much the same SQL query does appear elsewhere (except with order by clause).  Could it be put in a separate function call?

2025-03-26 12:56 UTC, NicholasHilken commented on PackManagement.php
>  		$this->dbGetLock();
Sorry - probably betraying some of my ignorance again here, but if we've initiated a db lock, and an exception occurs such that execution path drops out of the function before the $this->dbReleaseLock(); - is there a danger the db will be left locked?  Not sure of how the code will react in these circumstances, and what the default exception handling behaviour is here.  I know I've often seen db transactions done with try-catch, and a rollback if all is not well, just wondered if something similar may be beneficial here?

2025-03-26 12:59 UTC, NicholasHilken commented on PackManagement.php
> +		                                                 JSON_HEX_QUOT | JSON_HEX_APOS |
am I getting deja vu with this string of predefined constants like JSON_HEX_QUOT?  Should we have it all done once?

2025-03-26 13:00 UTC, NicholasHilken commented on PackManagement.php
> +		$queryCat = $this->query( 'SELECT ems.`value` AS category ' .
Is this the same as the other SQL that I remarked on?

2025-03-26 13:35 UTC, richdooley commented on PackManagement.php
>  		$this->dbGetLock();
The `dbGetLock()` function gets a MySQL named lock as described in the [MySQL locking functions documentation](https://dev.mysql.com/doc/refman/8.0/en/locking-functions.html).
This will wait for the lock with the specific name to become available and there is a timeout in case of an issue releasing a lock. The Pack Management module uses a specific lock name so these locks only affect the module and uses a timeout of 60 seconds.
```php
	public function dbGetLock()
	{
		$this->query( 'DO GET_LOCK(?,60)', [ $GLOBALS['db'] . '.pack_management' ] );
	}
```

2025-03-26 13:57 UTC, richdooley commented on PackManagement.php
> +		                                                 JSON_HEX_QUOT | JSON_HEX_APOS |
Here it's within a function so that's the intention.

2025-03-26 14:27 UTC, NicholasHilken commented on packs_list.php
> +						// Update the record.
For a pack exchange, I think it would be a good idea to have a pop up dialogue to confirm/cancel, just in case someone had selected 2 packs by accident - after all, the pack list is long and will not all be on screen at the same time.

2025-03-26 14:30 UTC, NicholasHilken requested changes
Some comments for consideration,, and possible future version, but confirm/cancel on pack exchange I think would be very important.

2025-03-26 14:36 UTC, richdooley commented on packs_list.php
> +						// Update the record.
It does this.

2025-03-26 14:41 UTC, richdooley commented on packs_list.php
> +						// Update the record.
Additionally the *Save* button becomes an *Exchange* button when 2 packs which can be exchanged are selected.

2025-03-27 13:23 UTC, NicholasHilken approved these changes
Thanks!

2025-04-04 20:25 UTC, shelbycastle approved these changes

2025-04-08 09:26 UTC, merged